Repository canonical/wordpress-k8s-operator, pull requests merged in 2023-10, with the labels that each got.

#142 Add retries to the wp theme list command
  .github/workflows/integration_test.yaml
  src/charm.py
Labels: bug, Libraries: Out of sync

#149 ci(digest): Add digest pinning
  renovate.json
Labels: Libraries: Out of sync, trivial

#141 Wordpress: Create a rockfile to replace the current Dockerfile
  .github/workflows/integration_test.yaml
  .gitignore
  src/charm.py
  wordpress.Dockerfile
  wordpress_rock/files/etc/apache2/apache2.conf
  wordpress_rock/files/etc/apache2/conf-available/docker-php-swift-proxy.conf
  wordpress_rock/files/etc/apache2/conf-available/docker-php.conf
  wordpress_rock/files/etc/apache2/sites-available/000-default.conf
  wordpress_rock/rockcraft.yaml
Labels: Libraries: Out of sync, complex

#151 remove integration-test-with-secrets and run those tests in integration-test
  .github/workflows/integration_test.yaml
Labels: Libraries: Out of sync, trivial

#132 chore: remove start event handler
  src/charm.py
Labels: Libraries: Out of sync, trivial

#155 Support non-default mysql database ports
  src/charm.py
  src/charm.pyi
  src/types_.py
  tests/unit/test_charm.py
  tests/unit/wordpress_mock.py
Labels: bug, Libraries: Out of sync

#154 Change uploads directory ownership
  src/charm.py
  tests/integration/test_core.py
  tests/unit/wordpress_mock.py
Labels: Libraries: Out of sync, trivial

#159 feat(cves): Remove ignored CVEs
  .github/workflows/autoremove_cves.yaml
Labels: Libraries: Out of sync, trivial

#157 Eliminate mysql-interface variables
  config.yaml
Labels: Libraries: Out of sync
