Repository canonical/wordpress-k8s-operator, pull requests merged in 2025-04, with the labels that each got.

#274 fix: openid relogin
  tests/integration/helper.py
  tests/integration/test_external.py
Labels: Libraries: Out of sync, trivial

#262 fix: yoastseo supported version
  .wokeignore
  docs/changelog.md
  wordpress_rock/rockcraft.yaml
Labels: bug, Libraries: OK, trivial

#281 chore: update apache exporter
  .trivyignore
  wordpress_rock/rockcraft.yaml
Labels: Libraries: Out of sync

#279 Update docs for exemplar status
  docs/explanation/charm-architecture.md
  docs/how-to/configure-initial-settings.md
  docs/how-to/contribute.md
  docs/how-to/enable-waf.md
  docs/how-to/index.md
  docs/how-to/retrieve-initial-credentials.md
  docs/how-to/upgrade.md
  docs/index.md
  docs/reference/actions.md
  docs/reference/configurations.md
  docs/reference/relation-endpoints.md
  docs/tutorial.md
Labels: documentation, Libraries: Out of sync

#282 Docs: Remove easy and simple from descriptions
  README.md
  docs/how-to/contribute.md
  docs/how-to/index.md
  docs/index.md
  metadata.yaml
Labels: documentation, Libraries: Out of sync
