Repository canonical/wordpress-k8s-operator, pull requests merged in 2025-03, with the labels that each got.

#259 Add `upload_max_filesize`, `post_max_size`, and `max_execution_time` configuration
  config.yaml
  lib/charms/nginx_ingress_integrator/v0/nginx_route.py
  src/charm.py
  tests/integration/test_core.py
  tests/unit/test_charm.py
  tests/unit/wordpress_mock.py
Labels: Libraries: Out of sync, trivial

#256 chore(doc): Add charm architecture
  docs/changelog.md
  docs/explanation/charm-architecture.md
  docs/explanation/containers.md
  docs/explanation/lifecycle-events.md
  docs/explanation/oci-image.md
  docs/explanation/overview.md
  docs/explanation/relations.md
  docs/index.md
  tests/unit/wordpress_mock.py
Labels: documentation, Libraries: Out of sync

#257 Docs: How-to landing and organization
  docs/how-to/index.md
  docs/index.md
Labels: documentation, Libraries: Out of sync

#268 Revert "[discourse-gatekeeper] Migrate charm docs"
  docs/changelog.md
  docs/explanation/charm-architecture.md
  docs/how-to/configure-hostname.md
  docs/how-to/configure-initial-settings.md
  docs/how-to/configure-object-storage.md
  docs/how-to/enable-waf.md
  docs/how-to/index.md
  docs/how-to/integrate-with-cos.md
  docs/how-to/retrieve-initial-credentials.md
  docs/how-to/rotate-secrets.md
  docs/how-to/upgrade-wordpress-charm.md
  docs/index.md
  docs/reference/actions.md
  docs/reference/configurations.md
  docs/reference/external-access.md
  docs/reference/integrations.md
  docs/reference/plugins.md
  docs/tutorial.md
Labels: Libraries: Out of sync

#272 Update docs for exemplar of good Charmhub documentation
  CONTRIBUTING.md
  docs/explanation/charm-architecture.md
  docs/how-to/configure-hostname.md
  docs/how-to/configure-initial-settings.md
  docs/how-to/configure-object-storage.md
  docs/how-to/contribute.md
  docs/how-to/enable-antispam.md
  docs/how-to/enable-waf.md
  docs/how-to/install-plugins.md
  docs/how-to/install-themes.md
  docs/how-to/integrate-with-cos.md
  docs/how-to/redeploy.md
  docs/how-to/retrieve-initial-credentials.md
  docs/how-to/upgrade-wordpress-charm.md
  docs/reference/actions.md
  docs/reference/configurations.md
  docs/reference/external-access.md
  docs/reference/integrations.md
  docs/reference/plugins.md
  docs/tutorial.md
Labels: documentation, Libraries: Out of sync
